services:
  - type: web
    name: athar-notes-api-ali-dev
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /note
    envVars:
      - key: DATABASE_URL
        sync: false
