services:
  - type: web
    name: athar-notes-api-ali-dev
    runtime: docker
    plan: free
    healthCheckPath: /note
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
